package ru.practicum.shareit.user.dto;

import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;
import ru.practicum.shareit.user.model.User;

import java.util.List;
import org.mapstruct.MappingConstants;

import javax.annotation.processing.Generated;

@Mapper(componentModel = MappingConstants.ComponentModel.SPRING)
@Generated("AutoGeneratedByMapStruct")
public interface UserMapper {

    UserMapper INSTANCE = Mappers.getMapper(UserMapper.class);

    UserDto toUserDto(User user);

    User toUser(UserDto userDto);

    List<UserDto> toUserDto(List<User> users);
}